### ISSUE TITLE
Resizing sections in create volumes pop-up

### ISSUE THREAD

**Issue by lelabbady** [TotteKarlsson/ATExplorer#12]
The window opened with create volumes, has a standard size for each column thus sometimes cuts off stack names and cannot be resized. Would be nice to either be able to resize it, or have it calculate and appropriate sizing based on name length

**Comment by TotteKarlsson** [comment]
Fixed with a splitter. Better would be if SW check the length of all names and adjust width from that, as suggested above.. open a new issue?
