### ISSUE TITLE
multi-tiff/png stack files not created

### ISSUE THREAD

**Issue by lelabbady** [TotteKarlsson/ATExplorer#13]
When creating volumes, the stack files are not being created...only the single z images are being saved on disk.

**Comment by TotteKarlsson** [comment]
This was a bug related to ImageMagick and the atClassifer program. The atClassifierProgram registered an invalid ImageMagick path environment variable, causing the tiffstack creation not working.
remove the environment variable, and stack cration works. The variable to remove is something like IMAGE_MAGIC_CODEC_PATH
