### ISSUE TITLE
ability to set up remote render hosts

### ISSUE THREAD

**Issue by lelabbady** [TotteKarlsson/ATExplorer#45]
all render hosts need to be set up (including local)
        - service (http)
        - backend (docker)

**Comment by TotteKarlsson** [comment]
A new UI version (0.7.0) was made with this new feature. Bunch of other functionality in 0.7.0 is broken for now however.

**Comment by lelabbady** [comment]
Tested on windows machine, using default ibs-forrest. Successfully requested service properties and existing owners
